-- In your Supabase project, navigate to the "SQL Editor" and run this script.

-- Create a table for your products
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_code TEXT NOT NULL,
  viet_name TEXT,
  eng_name TEXT,
  uom TEXT,
  photo_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- After creating the table, you might want to insert some sample data to test with.
-- You can run this in the SQL Editor as well.
-- INSERT INTO products (account_code, viet_name, eng_name, uom)
-- VALUES
--   ('ITEM001', 'Sản phẩm mẫu 1', 'Sample Product 1', 'Cái'),
--   ('ITEM002', 'Sản phẩm mẫu 2', 'Sample Product 2', 'Hộp');


-- INSTRUCTIONS FOR SUPERBASE STORAGE
-- 1. Go to your Supabase project dashboard.
-- 2. In the left sidebar, click on "Storage".
-- 3. Click the "New bucket" button.
-- 4. Enter 'photos' as the bucket name.
-- 5. For this project, you can make the bucket public for simplicity. Click "Create bucket".
-- 6. You will also need to create a policy to allow uploads to this bucket.
--    - Go to Storage -> Policies.
--    - Select the 'photos' bucket and click "New policy".
--    - You can create a policy that allows public inserts, or a more restrictive one
--      that only allows authenticated users to upload. For a simple start, you can
--      create a policy "For full customization" with a name like "Public Upload"
--      and use the following for the policy definition, which allows anyone to upload:
--
--      CREATE POLICY "Public Upload" ON storage.objects
--      FOR INSERT WITH CHECK ( bucket_id = 'photos' );
--
--      Or, for authenticated users only:
--
--      CREATE POLICY "Authenticated Upload" ON storage.objects
--      FOR INSERT TO authenticated WITH CHECK ( bucket_id = 'photos' );
--
--      Choose the policy that best fits your security requirements.
--      For this PWA, since we are not implementing user authentication yet,
--      a public upload policy is the most straightforward to get started.
--
--      To allow select (viewing) access on the bucket, you can create another policy:
--
--      CREATE POLICY "Public Select" ON storage.objects
--      FOR SELECT USING ( bucket_id = 'photos' );
