-- In your Supabase project, navigate to the "SQL Editor" and run this script.

-- Create a table for your packaging materials
CREATE TABLE packaging_material (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_code TEXT NOT NULL,
  viet_name TEXT,
  eng_name TEXT,
  uom TEXT,
  photo_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- After creating the table, you might want to insert some sample data to test with.
-- You can run this in the SQL Editor as well.
-- INSERT INTO packaging_material (account_code, viet_name, eng_name, uom)
-- VALUES
--   ('ITEM001', 'Vật liệu đóng gói mẫu 1', 'Sample Packaging Material 1', 'Cái'),
--   ('ITEM002', 'Vật liệu đóng gói mẫu 2', 'Sample Packaging Material 2', 'Hộp');


-- INSTRUCTIONS FOR SUPERBASE STORAGE
-- 1. Go to your Supabase project dashboard.
-- 2. In the left sidebar, click on "Storage".
-- 3. Click the "New bucket" button.
-- 4. Enter 'packaging_photo' as the bucket name.
-- 5. For this project, you can make the bucket public for simplicity. Click "Create bucket".
-- 6. You will also need to create a policy to allow uploads to this bucket.
--    - Go to Storage -> Policies.
--    - Select the 'packaging_photo' bucket and click "New policy".
--    - You can create a policy that allows public inserts.
--
--      CREATE POLICY "Public Upload" ON storage.objects
--      FOR INSERT WITH CHECK ( bucket_id = 'packaging_photo' );
--
--      To allow select (viewing) access on the bucket, you can create another policy:
--
--      CREATE POLICY "Public Select" ON storage.objects
--      FOR SELECT USING ( bucket_id = 'packaging_photo' );
