-- Minimal setup - no performance optimizations

-- Create the main packaging materials table
CREATE TABLE packaging_material (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_code TEXT NOT NULL,
  viet_name TEXT,
  eng_name TEXT,
  uom TEXT,
  weight NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  version TEXT,
  status TEXT,
  category TEXT,
  type TEXT,
  subtype TEXT,
  brand TEXT,
  market TEXT
);

-- Create the photos table with foreign key relationship
CREATE TABLE packaging_photo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_id BIGINT NOT NULL,
  image_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT packaging_photo_material_id_fkey 
    FOREIGN KEY (material_id) 
    REFERENCES packaging_material (id) 
    ON DELETE CASCADE
);


